version: '3.7'
networks:
  ink-explorer-network:
    external: true
services:
  backend:
    restart: on-failure
    depends_on:
     - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    networks:
      ink-explorer-network: 
        aliases:
          - "backend"
    env_file:
      - .env
  postgres:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ink
    networks:
      ink-explorer-network: 
        aliases:
          - "postgres"