version: '3.7'
networks:
  ink-explorer-network:
    name: ink-explorer-network
  default:
    driver: ink-explorer-network

services:
  backend:
    #image: blockcoders/ink-substrate-explorer-api:latest
    restart: on-failure
    depends_on:
      - postgres
    build:
      context: .
      # dockerfile: dev.Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
    networks:
      ink-explorer-network:
        aliases:
          - "backend"
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=ink
      - MONGO_INITDB_USER=mongodb
      - MONGO_INITDB_PWD=mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      ink-explorer-network:
        aliases:
          - "mongo"
