version: '3.7'
services:
  backend:
    restart: on-failure
    depends_on:
     - postgres
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks:
      - ink-substrate-explorer-api-network
    ports:
      - 8085:8085
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
  postgres:
    image: postgres:14.4
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ink
    networks:
      - ink-substrate-explorer-api-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - ink-substrate-explorer-api-network

networks:
  ink-substrate-explorer-api-network:
