import { Field, Int, ObjectType } from '@nestjs/graphql'
//import { GenericExtrinsicEra } from '@polkadot/types'
import { Block } from '../../blocks/entity/block.entity'
import { BaseEntity, Column, Entity, Index, JoinColumn, ManyToOne, OneToMany, PrimaryColumn } from 'typeorm'
import { Event } from 'src/events/entity/event.entity'

@ObjectType()
@Entity({ name: 'transactions' })
@Index(['signer'])
export class Transaction extends BaseEntity {
  @PrimaryColumn()
  @Field(() => String, { description: 'Transaction hash' })
  hash!: string

  @Column()
  @Field(() => String, { nullable: true })
  blockHash!: string

  @Column()
  @Field(() => String)
  method!: string

  @Column()
  @Field(() => String)
  section!: string

  @ManyToOne(() => Block, (block: Block) => block.transactions, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn()
  block!: Block

  @OneToMany(() => Event, (event: Event) => event.transaction, { nullable: true })
  events!: Event[]

  @Column()
  @Field(() => String, { description: 'Signature generated by the signer' })
  signature?: string

  @Column()
  @Field(() => String, { description: 'Address of the signer', nullable: true })
  signer?: string

  @Column('int')
  @Field(() => Int, { description: "Transaction's nonce", nullable: true })
  nonce?: number

  @Column('int')
  @Field(() => Int, { description: 'Extra gas paid for the Tx as tip', nullable: true })
  tip?: number

  // TODO: add this
  //era?: GenericExtrinsicEra
  // We are not storing this for now
  //args: any
}
