import { InputType, Int, Field } from '@nestjs/graphql'

@InputType()
export class CreateTransactionInput {
  @Field(() => String, { description: 'Transaction hash' })
  hash!: string

  @Field(() => String)
  blockHash!: string

  @Field(() => String)
  method!: string

  @Field(() => String)
  section!: string

  @Field(() => String, { description: 'Signature generated by the signer' })
  signature?: string

  @Field(() => String, { description: 'Address of the signer', nullable: true })
  signer?: string

  @Field(() => Int, { description: "Transaction's nonce", nullable: true })
  nonce?: number

  @Field(() => Int, { description: 'Extra gas paid for the Tx as tip', nullable: true })
  tip?: number
}
